Озмаден Дениз - ДЗ3
dozmaden/HSE-React-Course pull request #1
Opened 2020-10-20 20:34 UTC by dozmaden

Я запутался в ветках, но надеюсь это правильно и хлам я не закоммитил.
В след раз лучше разберусь и почищу здесь всё.

С уважением,
Озмаде

2020-10-20 20:42 UTC, dozmaden commented
Не могу добавить ревьювера, так что тегаю
@valerystatinov

2020-10-20 20:54 UTC, ValeryStatinov commented
а в коллабораторы добавлял меня?

2020-10-21 09:06 UTC, dozmaden commented
> а в коллабораторы добавлял меня?

Справедливо. Отправил запрос

2020-10-22 21:45 UTC, ValeryStatinov requested changes
удалить .idea и добавить в гитигнор

все файлы и папки связанные с проектов поднять на уровень выше, удалив папку `HW3`. этот проект ты будешь развивать в течение всего курса, а не только в дз3

по самой работе все хорошо. после этих небольших правок с репозиторием будет отл(10)

2020-10-22 21:45 UTC, ValeryStatinov commented on hw3/src/item.js
> +import React from 'react'
название файлов, содержащих компоненты принято писать с большой буквы

2020-10-24 12:20 UTC, dozmaden commented
Наконец-то у меня получилось красиво сделать (папку удалил, переименовал файл)

2020-10-24 12:21 UTC, ValeryStatinov commented
класс! после внесения правок перезапрашивай ревью в правом блоке, и в ближайшие дни все будет проверено)

2020-10-29 16:04 UTC, ValeryStatinov approved these changes
теперь все хорошо, отл(10)
желательно еще из ~~master~~ main удалить .idea и что-то еще там лишнее есть

2020-11-13 18:35 UTC, merged